---
title: "canna"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
runtime: shiny
---
```{r}
knitr::opts_chunk$set( echo=FALSE, warning=FALSE, message=FALSE)
encoding = "Latin1"
```


```{r}
library(flexdashboard)
library(readxl)
library(ggplot2)
library(stringr)
library(plotly)
library(DT)
library(knitr)
library(shiny)
# library(shinyWidgets)
library(lubridate)
library(tidyverse)
library(janitor)
library(scales)
library(readr)
library(highcharter)
# library(googledrive)
library(googlesheets4)
```
```{r}
vitimas  <- read_delim("Mortes_Violentas.csv",
    delim = ";", escape_double = FALSE, locale = locale(encoding = "Latin1"),
    trim_ws = TRUE) %>% clean_names()

vitimas <- vitimas %>% mutate(incidente = if_else(startsWith(incidente, "LES"), "LESÃO CORPORAL SEGUIDA DE MORTE", incidente))%>%
  rename(
    data = data_do_obito
    )


```


```{r cars, include=FALSE}
dados<- read_delim("MICRODADOS_OCORRENCIAS.csv",
    delim = ";", escape_double = FALSE, locale = locale(encoding = "Latin1"),
    trim_ws = TRUE)%>% clean_names()
dados <- dados %>% select(data, tipo_incidente, municipio)%>%
  rename(
    incidente = tipo_incidente
    )

dados_homicidio <- vitimas %>% select(data, incidente, municipio) %>% mutate(data = parse_date_time(data, "dmy"))

dados_crimes <- rbind( dados_homicidio,dados) %>% filter(data> "2017-12-31")

# write.csv(dados_crimes,"dados_crimes.csv")







# dados <- dados %>% filter(incidente == "ROUBO: EM RESIDÊNCIA/CONDOMÍNIO")

# dados_react <- reactive( dados %>% filter(municipio == input$cidade, incidente == input$tipo))

dados_react <- reactive( dados_crimes %>% filter(municipio == input$cidade, incidente  %in% c(input$tipo)))


```

Column {.sidebar}
-----------------------------------------------------------------------


```{r}
# sliderInput("hora","hora", min = 0, max = 23, value = c(00,23))

selectInput("cidade","cidade", choices = unique(dados_crimes$municipio), selected = "SANTA TERESA")

checkboxGroupInput("tipo","Tipo de Crime",unique(dados_crimes$incidente), selected = unique(dados_crimes$incidente) )
```


Row
-----------------------------------------------------------------------
### dados

```{r}

renderDT(datatable(dados_react() %>% group_by( incidente) %>% count()))

```




Row
-----------------------------------------------------------------------
### plot
```{r}
renderPlotly(
  
  ggplot(dados_react(), aes(year(data), fill = incidente)) + geom_bar()
  

  
)
```


### cidade
```{r}

perigosas  <- dados_crimes %>% group_by(municipio) %>% summarise(total = n()) %>% mutate (municipio = fct_reorder(municipio,total))
 # head(arrange(perigosas,-total),10)

renderPlotly(

    ggplot(head(arrange(perigosas,-total),10), aes(x=municipio, y=total)) +
    geom_bar(stat="identity", fill="#f68060", alpha=.6, width=.4) +
    coord_flip() +
    xlab("") +
    theme_bw()

)
```
